### ISSUE TITLE
How far along is this project 

### ISSUE THREAD

**Issue by RyzenDew** [DavidSM64/Diddy-Kong-Racing#241]
What % is this project?

**Comment by Ryan-Myers** [comment]
All progress is listed in the README file for this project. Please do not open issues for questions like this.

**Comment by RyzenDew** [comment]
Does not say a thing about how far along you are .. most decomps for n64 have progress amount

**Comment by DavidSM64** [comment]
As it says in the README, we are 28.87% complete with the decomp.
![Untitled](https://user-images.githubusercontent.com/12130403/185977156-3e75ce0b-0998-4d27-84aa-8aab00393aee.png)
.
