### ISSUE TITLE
Add license or SPDX

### ISSUE THREAD

**Issue by superbonaci** [DavidSM64/Diddy-Kong-Racing#398]
Hi, which license is going to be this project?

**Comment by DavidSM64** [comment]
Was always kinda iffy on making a license, but I guess it would be better to do it now rather than later. I'm planning to make it CC0 if all the contributors agree.

**Comment by Ryan-Myers** [comment]
I'll agree.

**Comment by superbonaci** [comment]
I've seen that https://github.com/sm64pc/sm64ex doesn't have a license either, so maybe it's the norm for decompiled code.

**Comment by DavidSM64** [comment]
> I've seen that https://github.com/sm64pc/sm64ex doesn't have a license either, so maybe it's the norm for decompiled code.

The decomp repo added the license as CC0 around 5 months ago, and I guess the PC version didn't get updated. You can find the license here:  https://github.com/n64decomp/sm64/blob/master/LICENSE.md
