### ISSUE TITLE
DKR decomp licensing (CC0)

### ISSUE THREAD

**Issue by DavidSM64** [DavidSM64/Diddy-Kong-Racing#399]
Shamelessly copying the SM64 decomp's license of CC0. I'd like to have all the past contributors agree to the license change and share their past contributions before it becomes official.

**Which license?**
CC0 is a license that seems to fit the unofficial stance.

It can be thought of as "public domain", or a more robust version of the Unlicense.

It also has the added benefit that it does not consist of a copyright affirmation, which is good given the murky waters decompilation is in.

**Read about CC0:**
https://creativecommons.org/publicdomain/zero/1.0/
https://choosealicense.com/licenses/cc0-1.0/
https://wiki.creativecommons.org/wiki/CC0_FAQ

**Comment by Ryan-Myers** [comment]
Agreed

**Comment by DavidSM64** [comment]
@Ryan-Myers @FazanaJ @Faschz @AntonioCastelli @MittenzHugg @tonyspumoni @RenaKunisaki @queueRAM @ChrisNonyminus @Turok64Nukem

**Comment by DavidSM64** [comment]
I agree to share all my contributions to the DKR decomp under CC0.

**Comment by FazanaJ** [comment]
I consent to any and all changes regarding licensing

**Comment by RenaKunisaki** [comment]
I consent to any and all changes regarding licensing.

**Comment by queueRAM** [comment]
For all my alleged contributions to DKR decomp which are not already released under a different licenses, I agree to license them under CC0.

**Comment by AntonioCastelli** [comment]
I consent. Let 'er rip, bud

**Comment by Faschz** [comment]
I agree to share all my contributions under CC0.

**Comment by MittenzHugg** [comment]
I consent

**Comment by Turok64Nukem** [comment]
We're all good I confirm.

**Comment by DavidSM64** [comment]
Thanks everyone!
